
export enum WarmingType{
  CENTRAL_HEATING="CENTRAL_HEATING",
  INFRARED_HEATING="INFRARED_HEATING",
  ELECTRIC_HEATING="ELECTRIC_HEATING",
  NATURAL_GAS_HEATING="NATURAL_GAS_HEATING",
  FIREPLACE_AND_WOOD_STOVE="FIREPLACE_AND_WOOD_STOVE"
}
